<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
	  <GraphQL Remove="GraphQL\Queries\CreateCourse.graphql" />
	</ItemGroup>

	<ItemGroup>
	  <None Remove="GraphQL\Mutations\DeleteCourse.graphql" />
	  <None Remove="GraphQL\Mutations\UpdateCourse.graphql" />
	  <None Remove="GraphQL\Queries\GetCourseById.graphql" />
	  <None Remove="GraphQL\Queries\GetInstructors.graphql" />
	  <None Remove="GraphQL\Subscriptions\CourseCreated.graphql" />
	  <None Remove="GraphQL\Subscriptions\CourseUpdated.graphql" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="FirebaseAuthentication.net" Version="4.1.0" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="8.0.8" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="8.0.8" PrivateAssets="all" />
		<PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="8.0.8" />
		<PackageReference Include="MudBlazor" Version="7.7.0" />
		<PackageReference Include="Refit.HttpClientFactory" Version="7.1.2" />
		<PackageReference Include="Refit.Newtonsoft.Json" Version="7.1.2" />
		<PackageReference Include="StrawberryShake.Blazor" Version="13.9.11" />
		<PackageReference Include="StrawberryShake.Transport.WebSockets" Version="13.9.11" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\BlazorLaboratory.Shared\BlazorLaboratory.Shared.csproj" />
	</ItemGroup>

</Project>